### PR TITLE
Update service worker

### PR DESCRIPTION
**Pull request by alabobriggs**
Below is the summary of the changes made

**SERVICE-WORKER.JS file**
The ```service-worker.js``` file code was restructured for better readability and support for automatic update was added.When a fetch request is made, a network call is made by the function ```makeNetWorkRequest``` if it fails then it falseback to getting a response from the cache using this the ```returnFromCache``` function. If ```returnFromCache``` call does't find a matching request then a fallback page ```offline.html``` is returned

**MANIFEST.JSON file**
The links to the icons wasn't linked currectly, adding a ```/src``` before the url starts fixes that

**OFFLINE.HTML file**
This is the fallback file if a request fails both on network and does not match any request in the cache. It uses only files that were cached previously are on index.html file.

### CODE REVIEW

**Comment by nerdeveloper** [comment]
Hello @alabobriggs Thank you for this! 

I did not see the *beforeinstallprompt*  event in your PWA.

flipkart-homescreen-708x1264

Kindly work on this and wait for a review. Thank you!

**Comment by alabobriggs** [comment]
I will update this now, I thought it was done automatically by the browser.

Is there a staging url I can use to test the app on mobile. @nerdeveloper

**Comment by nerdeveloper** [comment]
Oh, you cannot run service worker over localhost or unencrypted connections. 

Due to this, we employ webhooks. use https://ngrok.com.

Link: https://www.npmjs.com/package/ngrok

 if you are still confused, let me know.

**Comment by alabobriggs** [comment]
You can run service worker over localhost as localhost is considers a secure network .https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers I was able to install the app on my desktop. The problem comes with testing on mobile. What am confused about is if there is a url I can push to and test on mobile.

**Comment by nerdeveloper** [comment]
yeah, I was not discreet enough, you need an encrypted connection for a PWA to work perfectly.

**Comment by alabobriggs** [comment]
Thanks for the guide. This is the code that will be implemented 
```
       const divInstall = document.getElementById('installContainer');
        const butInstall = document.getElementById('butInstall');
       let deferredPrompt;
        window.addEventListener('appinstalled', (event) => {
            console.log('👍', 'appinstalled', event);
        });

        window.addEventListener('beforeinstallprompt', function(event) {
            // Prevent Chrome 67 and earlier from automatically showing the prompt
            event.preventDefault();
            // Stash the event so it can be triggered later.
            deferredPrompt = event;
        });

        butInstall.addEventListener('click',async () => {
            console.log('👍', 'butInstall-clicked');
            if (!deferredPrompt) {
                console.log(deferredPrompt)
                console.log('no prompt')
                return;
            }
            // Show the install prompt.
            deferredPrompt.prompt();
            // Log the result
            const installResult = await deferredPrompt.userChoice
            console.log('👍', 'userChoice',installResult);
            deferredPrompt = null;
        });
```

**Comment by nerdeveloper** [comment]
I am getting a notification that you update the PR, I can't seem to find it? did you?

**Comment by alabobriggs** [comment]
Yea I mistakenly made a comment which I deleted. I was trying to clarify an approach. Am working on another now

**Comment by alabobriggs** [comment]
I've been able to find solution using _beforeinstallprompt_ with help from the internet. This is the code below
```
const divInstall = document.querySelector('#installContainer');
        const butInstall = document.querySelector('#butInstall');
        let deferredPrompt;
        window.addEventListener('appinstalled', (event) => {
            console.log('👍', 'appinstalled', event);
        });

        window.addEventListener('beforeinstallprompt', (event) => {
            event.preventDefault()
            deferredPrompt = event;
            showAddToHomeScreen();
        });
        
        const showAddToHomeScreen = () => {
            butInstall.addEventListener("click", addToHomeScreen);
        }

        const addToHomeScreen = async () => {
            console.log('👍', 'butInstall-clicked');
            divInstall.classList.toggle('hidden', true);
            if (!deferredPrompt) {
                return;
            }
            try {
                await deferredPrompt.prompt();
                const installResult = await deferredPrompt.userChoice
                console.log('👍', 'userChoice', installResult);
                deferredPrompt = null;
            }
            catch (error) {
                console.error(error)
            }
        }
```
where am confused is how to add the button on the page. Is there an existing design of the prompt that will be shown to the user to install .
I tried using a ```setTimeout``` to click the install button automatically but I was getting an error.

**Comment by nerdeveloper** [comment]
Does it work? do you have pictures or something

**Comment by alabobriggs** [comment]
No the timeout doesn't work. A DOMexception error is thrown. Am trying another method now.

Is there an existing design for the prompt just incase it can't be triggered automatically

**Comment by nerdeveloper** [comment]
Also, there is no need for an existing design, it communicates with your browser, not your web app. i.e you are interfacing with the browser(chrome) API directly. 

> I've been able to find solution using _beforeinstallprompt_ with help from the internet. This is the code below
> 
> ```
> const divInstall = document.querySelector('#installContainer');
>         const butInstall = document.querySelector('#butInstall');
>         let deferredPrompt;
>         window.addEventListener('appinstalled', (event) => {
>             console.log('👍', 'appinstalled', event);
>         });
> 
>         window.addEventListener('beforeinstallprompt', (event) => {
>             event.preventDefault()
>             deferredPrompt = event;
>             showAddToHomeScreen();
>         });
>         
>         const showAddToHomeScreen = () => {
>             butInstall.addEventListener("click", addToHomeScreen);
>         }
> 
>         const addToHomeScreen = async () => {
>             console.log('👍', 'butInstall-clicked');
>             divInstall.classList.toggle('hidden', true);
>             if (!deferredPrompt) {
>                 return;
>             }
>             try {
>                 await deferredPrompt.prompt();
>                 const installResult = await deferredPrompt.userChoice
>                 console.log('👍', 'userChoice', installResult);
>                 deferredPrompt = null;
>             }
>             catch (error) {
>                 console.error(error)
>             }
>         }
> ```
> 
> where am confused is how to add the button on the page. Is there an existing design of the prompt that will be shown to the user to install

There is no need for a design. you are interfacing with the browser(chrome) API directly.

**Comment by alabobriggs** [comment]
Screenshot from 2019-10-04 11-13-48


I added an test install button next to dsc logo which when I click it the inbuilt install prompt show but if I try to click the button using js i'e. ```btnInstall.click()``` I get a DOMexception error. From the research made it was said that ```deferedPrompt.prompt()``` can only be called with a user gestrure that is why it works when I click the button directly but not when I do that using js. 

I think I might need to add a popup at the bottom that tells the user to install which will then trigger the inbuilt install prompt or is there a way to trigger it without a user gesture

**Comment by nerdeveloper** [comment]
this should be your solution. try this:

```
let deferredPrompt;

function addToHomeScreen() {
    const a2hsBtn = document.querySelector(".ad2hs-prompt"); // hide our user interface that shows our A2HS button
    a2hsBtn.style.display = "none"; // Show the prompt
    deferredPrompt.prompt(); // Wait for the user to respond to the prompt
    deferredPrompt.userChoice.then(function(choiceResult) {
        if (choiceResult.outcome === "accepted") {
            console.log("User accepted the A2HS prompt");
        } else {
            console.log("User dismissed the A2HS prompt");
        }

        deferredPrompt = null;
    });
}
function showAddToHomeScreen() {
    var a2hsBtn = document.querySelector(".ad2hs-prompt");

    a2hsBtn.style.display = "block";

    a2hsBtn.addEventListener("click", addToHomeScreen);
}

window.addEventListener("beforeinstallprompt", function(e) {
    // Prevent Chrome 67 and earlier from automatically showing the prompt
    e.preventDefault();
    // Stash the event so it can be triggered later.
    deferredPrompt = e;

    showAddToHomeScreen();
});

```

**Comment by alabobriggs** [comment]
Yes that is the solution but a **button on the page** needs to be clicked. Even from your code an button with class _.ad2hs-prompt_ needs to be clicked. Now this button isn't on the page and it has to be added on the page like a first prompt then when the user clicks this the inbuilt chrome prompt will pop up then it can be install. 
Where the solutions is is to add the button to the page, hence a design for the custom prompt is needed since it cannot be clicked using js.

I believe the problem can be solved if the _install button_ can be clicked using javascript and it won't return an error, this what am trying to find out now

**Comment by alabobriggs** [comment]
Referencing this  [example from mdn](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent/prompt#Example) it still throws a DOMexception error. This is probably a bug or feature targeted at user experience to stop the automatic prompt without user gesture.

**Comment by nerdeveloper** [comment]
since this is uncertain. Remove the *beforeinstallprompt* for now. I am impressed @alabobriggs 

Then share me screenshots of your working app so that I can merge this. Thank you for the hard work!

**Comment by alabobriggs** [comment]
Thanks for the guide. The add to screen feature have been added. It appears I was trying to solve a desktop issue that was never there. Below is the screenshot of the working app
Screenshot from 2019-10-04 13-50-16
Screenshot from 2019-10-04 13-50-57




WhatsApp Image 2019-10-04 at 1 46 50 PM (3)
WhatsApp Image 2019-10-04 at 1 46 50 PM (2)
WhatsApp Image 2019-10-04 at 1 46 50 PM (1)
WhatsApp Image 2019-10-04 at 1 46 50 PM

**Comment by nerdeveloper** [comment]
I am sure you have learnt a lot from this. I am happy you did this. Thank you for an amazing job!

**Pull request merged**
