### PR TITLE
create icons folder

### PR DESCRIPTION
**Pull request by miracleonyenma**
with icon.txt

### CODE REVIEW

**Comment by nerdeveloper** [comment]
hello @miracleonyenma, You submitted an empty PR. Kindly fix.

**Comment by miracleonyenma** [comment]
uploaded the following files
icon512
44x44
48x48
88x88
150x150
300x300
1240x600

**Comment by nerdeveloper** [comment]
Wow! @miracleonyenm. I am happy with the work you have done here. Please, delete the *icons.txt* file and rename the *icon512.png* to *512x512.png*

**Comment by nerdeveloper** [comment]
hello @miracleonyenma delete the *icons.txt* file

**Comment by nerdeveloper** [comment]
Hay @miracleonyenma . You've done an amazing job here. I am really happy you took your time to do follow instructions. You are officially an open source chief 🎊

**Pull request merged**
